[project]
name = "clean"
version = "0.1.0"
description = "Data analysis for Juju's Game of Life"
requires-python = ">=3.13"
dependencies = [
    "ipython>=9.6.0",
    "numpy>=2.3.4",
    "pillow>=12.0.0",
]
